[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-martim.json"

[target.'cfg(target_os = "none")']
runner = "cargo run -Zbuild-std --target=x86_64-apple-darwin --package boot --" # run the boot sub-crate as runner
